charts/hwameistor/templates/local-storage-csi-sidecar.yaml, charts/hwameistor/values.yaml
=> Update registrar image and update member image

charts/hwameistor/values.yaml
=> Update registrar image

charts/hwameistor/values.yaml
=> fix: update scheduler image into hwameistor/scheduler:v0.0.3

README.md, charts/hwameistor/values.yaml
```
Enrich readme for both enable HwameiStor and claim disk
```
```release-note
```
=> Enrich readme for both enable HwameiStor and claim disk

charts/hwameistor/values.yaml
Update ldm image tag
NONE
```release-note
NONE
```
=> update ldm image tag

charts/hwameistor/values.yaml
```
fix k8s csi sidecar image repo
```
```release-note
```
=> Fix k8s csi sidecar image repo

charts/hwameistor/values.yaml
change local-storage image tag from v0.0.3 to v0.0.2 because v0.0.2 is meaningful at this moment
```release-note
```
=> change local-storage image tag to v0.0.2

charts/hwameistor/templates/local-storage-driver.yaml
the typo cause failure in deploy
fix: https://github.com/hwameistor/helm-charts/issues/15
```release-note
```
=> fix typo in the local-storage-driver template

charts/hwameistor/templates/local-disk-manager-controller.yaml
I found we has an unnecessary image pull secert in LDM yaml
```release-note
```
=> remove unnecessary image pull secert

charts/hwameistor/templates/local-storage-csi-sidecar.yaml, charts/hwameistor/templates/local-storage-driver.yaml
change some words since compatibility
```release-note
```
=> change word localstorage to lvm somewhere

charts/hwameistor/values.yaml
```
update temp scheduler version into v0.0.4, that deal with the csi driver name change
```
```release-note
```
=> update temp scheduler version into v0.0.4, that deal with the csi driver name change

charts/hwameistor/Chart.yaml
update to version to 0.2.4 and apply latest helm charts
```release-note
```
=> update version to 0.2.4

charts/hwameistor/Chart.yaml, charts/hwameistor/values.yaml
we fix bugs bugs of local-storage:v0.0.2 in local-storage:v0.1.1,and release a new chart version to apply it
```release-note
```
=> update local-storage image tag

README.md, charts/hwameistor/templates/local-storage-csi-controller.yaml
sync the affinity key-value in csi-controller with other modules, and update README.md to apply the newest installing manual
```release-note
```
=> update readme and affinity in csi-controller

charts/hwameistor/Chart.yaml
update version to 0.2.6 to release the newest charts in helm repo
```release-note
```
=> update version to 0.2.6

charts/hwameistor/templates/local-disk-manager.yaml, charts/hwameistor/templates/local-storage-csi-controller.yaml, charts/hwameistor/templates/local-storage.yaml, charts/hwameistor/templates/scheduler.yaml, charts/hwameistor/values.yaml
we separate image value to three parts:registry, name,tag for flexibility
```release-note
```
=> seprate image values to registry,name,tag

charts/hwameistor/templates/local-disk-manager.yaml, charts/hwameistor/templates/local-storage-csi-controller.yaml, charts/hwameistor/templates/local-storage.yaml, charts/hwameistor/values.yaml
tolerations in templates can turn on/off now
```release-note
```
=> tolerations can switch

charts/hwameistor/values.yaml
we add image registries option as comments so that users can switch to them if they need
```release-note
```
=> add image registry option

charts/hwameistor/templates/local-storage-csi-controller.yaml
we change some words for accuracy
```release-note
```
=> rename csi-controller to local-storage-csi-controller

charts/hwameistor/Chart.yaml, charts/hwameistor/values.yaml
we release the updating of image tags of scheduler and local-storage in 0.2.7
```release-note
```
=> update image tags and release 0.2.7

charts/hwameistor/Chart.yaml, charts/hwameistor/values.yaml
Signed-off-by: Niu Lechuan <lechuan.niu@daocloud.io>
```
Re-trigger the release action. that was disabled when PR(https://github.com/hwameistor/helm-charts/pull/36) created.
```
```release-note
```
=> Re-trigger the release action

doc/roadmap.md
we add a roadmap
```release-note
```
=> add roadmap

charts/hwameistor/crds/hwameistor.io_localdiskclaims_crd.yaml, charts/hwameistor/crds/hwameistor.io_localdisknodes_crd.yaml, charts/hwameistor/crds/hwameistor.io_localdisks_crd.yaml, charts/hwameistor/crds/hwameistor.io_localdiskvolumes_crd.yaml, charts/hwameistor/templates/local-disk-manager-csi-controller.yaml, charts/hwameistor/templates/local-disk-manager.yaml, charts/hwameistor/values.yaml
support deploy csi driver of local-disk-manager
```release-note
start use disk-volume in hwameistor ~
```
=> update: support deploy csi driver of local-disk-manager

charts/hwameistor/values.yaml
fix deploy error caused by pull local-disk-manager:latest failed
```release-note
```
=> update ldm image tag to v0.1.3

charts/hwameistor/Chart.yaml, charts/hwameistor/templates/scheduler-config.yaml, charts/hwameistor/values.yaml
release v0.2.8, update releated image tag and config
```release-note
1. update helm-charts version to v0.2.8
2. update local-disk-manager image tag to v0.1.4
3. update scheduler image tag to v0.1.4
4. modify scheduler apiVersion from v1beta2 to v1alpha1
```
=> release v0.2.8

charts/hwameistor/Chart.yaml, charts/hwameistor/values.yaml
update helm chart version to v0.2.9
```release-note
```
=> update helm chart version to v0.2.9

charts/hwameistor/crds/hwameistor.io_localvolumegroups_crd.yaml
fix: add lvg crd fix
```release-note
```
=> fix: add lvg crd fix

charts/hwameistor/templates/NOTES.txt, charts/hwameistor/templates/scheduler-config.yaml
show install message and the steps to use hwameistor
```release-note
```
=> add install notes

charts/hwameistor/Chart.yaml, charts/hwameistor/templates/NOTES.txt, charts/hwameistor/templates/local-disk-manager-csi-controller.yaml, charts/hwameistor/templates/local-disk-manager.yaml, charts/hwameistor/templates/local-storage-csi-controller.yaml, charts/hwameistor/templates/local-storage.yaml, charts/hwameistor/templates/scheduler-config.yaml, charts/hwameistor/templates/scheduler.yaml, charts/hwameistor/values.yaml
update local-disk-manager, local-storage, scheduler version
```release-note
NONE
```
=> release hwameistor-0.2.10.rc.0

charts/hwameistor/crds/hwameistor.io_localstoragenodes_crd.yaml, charts/hwameistor/crds/hwameistor.io_localvolumegroupmigrates_crd.yaml, charts/hwameistor/crds/hwameistor.io_localvolumegroups_crd.yaml, charts/hwameistor/crds/hwameistor.io_localvolumes_crd.yaml
update volumegroupmigrate crd
```release-note
NONE
```
=> update volumegroupmigrate crd

charts/hwameistor/values.yaml
update scheduler to v0.1.6-rc.3
```release-note
```
=> update scheduler to v0.1.6-rc.3

charts/hwameistor/crds/hwameistor.io_localvolumegroupconverts_crd.yaml
fix: add-lvgc-crd-file
```release-note
```
=> fix: add-lvgc-crd-file

charts/hwameistor/templates/local-disk-manager-csi-controller.yaml, charts/hwameistor/templates/local-disk-manager.yaml, charts/hwameistor/values.yaml
optional install local-disk-manager CSI by use enableCSI flag
default value is true
```release-note
NONE
```
=> update: optional install local-disk-manager CSI by use enableCSI flag

charts/hwameistor/crds/hwameistor.io_localdiskvolumes_crd.yaml
=> update localdiskvolume crd

charts/hwameistor/templates/_helpers.tpl, charts/hwameistor/templates/scheduler-config.yaml
=> fix: update scheduler image tag suffix pre1.18 => pre1.20

charts/hwameistor/Chart.yaml, charts/hwameistor/values.yaml
release hwameistor-0.2.9
```release-note
```
=> release hwameistor-0.2.9
